language: php

# Versions of PHP you want your project run with.

php:
  - 7.3
# Commands to be run before your environment runs.

before_script:
  - composer install --no-interaction
  - composer dump-autoload

# Commands you want to run that will verify your build.

env:
  - CODECOV_TOKEN="6effcfa8-1979-4840-858b-8dc30b3f401e" AUTENTIQUE_TOKEN="801a467bbd38cbdf152744362fbb51bfc27345ea7a5937f5241966cbea8e96dd" AUTENTIQUE_URL="https://api.autentique.com.br/v2/graphql" AUTENTIQUE_DEV_MODE="true"

script:
  - phpunit tests

after_script:
  - bash <(curl -s https://codecov.io/bash)

# allow_failures: Allow this build to fail under the specified environments.

# fast_finish: If your build fails do not continue trying to build, just stop.

matrix:
  allow_failures:
    - php: 7.3
  fast_finish: true