language: php

# Versions of PHP you want your project run with.

php:
  - 7.3
# Commands to be run before your environment runs.

before_script:
  - composer install --dev
  - composer dump-autoload
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# Commands you want to run that will verify your build.

env:
  - CC_TEST_REPORTER_ID="3cf8178110f1349a55cd0055a7e5cbf4c180aaa54d07b4455f93456b3f51ac68" AUTENTIQUE_TOKEN="1AAA95DCA22EAD45836A01A561BCE34B36DEF038CCC59B07A04670305F4834A6" AUTENTIQUE_URL="https://api.autentique.com.br/v2/graphql" AUTENTIQUE_DEV_MODE="true"

script:
  - phpunit tests
  - bundle exec rspec

after_script:g
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# allow_failures: Allow this build to fail under the specified environments.

# fast_finish: If your build fails do not continue trying to build, just stop.

matrix:
  allow_failures:
    - php: 7.3
  fast_finish: true

# Customize when the notification emails are sent.

notifications:
  on_success: never
  on_failure: always