name: Deploy Markdown to gh-pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Install phpDocumentator
      run: |
        make phpdoc-install
        make phpdoc-generate

    - name: Copy Markdown files
      run: |
        mkdir -p ${{ github.workspace }}/tmp-markdown
        cp -R ./docs/* ${{ github.workspace }}/tmp-markdown/
        cp -R ./phpdoc/ ${{ github.workspace }}/tmp-markdown/

    - name: Checkout gh-pages branch
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        path: gh-pages

    - name: Update gh-pages branch
      run: |
        rm -rf ./gh-pages/*
        cp -R ${{ github.workspace }}/tmp-markdown/* ./gh-pages/ # Copy Markdown to gh-pages
        cd gh-pages
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update Markdown files" || echo "No changes to commit"
        git push

    - name: Clean up
      run: rm -rf ${{ github.workspace }}/tmp-markdown
